# Site settings
title: Some impressions about the books  "Testing Statistical Hypotheses" and "Theory of Point Estimation"
email: alexej.go@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of random facts I observed while reading Lehmann's 
  "Testing Statistical Hypotheses" and "Theory of Point Estimation"
baseurl: "/Lehmanns_TSH_and_TPE" # the subpath of your site, e.g. /blog/
url: "http://www.alexejgossmann.com/" # the base hostname & protocol for your site
github_username: agisga 

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments
permalink: /:title/
gems:
  - jemoji # Enable emoji
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
